version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    env_file:
      - apps/streamer-backend/.env
    restart: always

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - apps/streamer-worker/.env
    restart: always
