packages:
  - "apps/*"
allowBuilds:
  '@nestjs/core': false
  '@prisma/engines': false
  '@scarf/scarf': false
  bcrypt: false
  ffmpeg-static: false
  msgpackr-extract: false
  prisma: false
  unrs-resolver: true
