packages:
  - "apps/*"
shamefullyHoist: true
allowBuilds:
  '@nestjs/core': false
  '@prisma/engines': false
  '@scarf/scarf': false
  bcrypt: false
  ffmpeg-static: true
  ffprobe-static: true
  msgpackr-extract: false
  prisma: false
  unrs-resolver: true
