import type { Movie, Genre, SubscriptionPlan } from "../types";

export const MOCK_GENRES: Genre[] = [
  { id: "1", name: "Action & Adventure", slug: "action" },
  { id: "2", name: "Sci-Fi & Fantasy", slug: "sci-fi" },
  { id: "3", name: "Drama & Suspense", slug: "drama" },
  { id: "4", name: "Comedy & Romance", slug: "comedy" },
  { id: "5", name: "Documentaries", slug: "docs" },
];

export const MOCK_MOVIES: Movie[] = [
  {
    id: "tears-of-steel",
    title: "Tears of Steel",
    description: "In an alternate dystopian future, a group of scientists and soldiers reunite in the Oude Kerk in Amsterdam to save the world from destructive giant robots.",
    thumbnailUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80",
    videoUrl: "https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8",
    duration: 734, // 12 mins
    releaseYear: 2024,
    rating: "PG-13",
    genres: ["Sci-Fi & Fantasy", "Action & Adventure"],
    isTrending: true,
    isPopular: true,
    cast: ["Derek de Lint", "Sergio Hasselbaink", "Rogier Schippers"],
    director: "Ian Hubert",
    matchPercentage: 99,
    qualityTags: ["4K", "Ultra HD", "5.1", "HDR"],
  },
  {
    id: "cyberpunk-neon",
    title: "Neon Horizon: 2099",
    description: "A rogue synthetic bounty hunter discovers a coded memory crystal detailing a corporate conspiracy that threatens to purge the cyber-slums of Neo-Tokyo.",
    thumbnailUrl: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80",
    videoUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8", // Big Buck Bunny HLS
    duration: 5400,
    releaseYear: 2025,
    rating: "18+",
    genres: ["Sci-Fi & Fantasy", "Action & Adventure"],
    isTrending: true,
    isPopular: false,
    cast: ["Kenji Takahashi", "Elena Rostova", "Marcus Vance"],
    director: "Lana Wachowski",
    matchPercentage: 96,
    qualityTags: ["1080p", "Dolby Atmos", "HDR"],
  },
  {
    id: "stranger-currents",
    title: "Stranger Currents",
    description: "When electrical anomalies lock down a remote coastal weather observatory, four childhood friends trace the phenomenon to a sunken cold-war research submarine.",
    thumbnailUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80",
    videoUrl: "https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8",
    duration: 3600,
    releaseYear: 2026,
    rating: "16+",
    genres: ["Drama & Suspense", "Sci-Fi & Fantasy"],
    isTrending: false,
    isPopular: true,
    cast: ["Millie Brown", "David Harbour", "Winona Ryder"],
    director: "The Duffer Brothers",
    matchPercentage: 92,
    qualityTags: ["1080p", "Dolby Vision"],
  },
  {
    id: "dune-prophecy",
    title: "Dune: Prophecy of Sand",
    description: "Set ten thousand years before the ascension of Paul Atreides, follow two Harkonnen sisters as they combat forces that threaten the future of humankind.",
    thumbnailUrl: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=800&q=80",
    videoUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    duration: 7200,
    releaseYear: 2025,
    rating: "PG-13",
    genres: ["Sci-Fi & Fantasy", "Drama & Suspense"],
    isTrending: true,
    isPopular: true,
    cast: ["Emily Watson", "Olivia Williams", "Travis Fimmel"],
    director: "Denis Villeneuve",
    matchPercentage: 98,
    qualityTags: ["4K", "Dolby Atmos"],
  },
  {
    id: "interstellar-voyage",
    title: "The Interstellar Voyage",
    description: "A crew of rogue astronauts embark on a high-stakes expedition through a newly materialized spatial anomaly in search of resources to stabilize a failing lunar outpost.",
    thumbnailUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
    videoUrl: "https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8",
    duration: 8400,
    releaseYear: 2023,
    rating: "PG-13",
    genres: ["Sci-Fi & Fantasy", "Drama & Suspense"],
    isTrending: false,
    isPopular: true,
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    director: "Christopher Nolan",
    matchPercentage: 95,
    qualityTags: ["Ultra HD", "5.1"],
  },
  {
    id: "arctic-darkness",
    title: "Arctic Darkness",
    description: "A deep-sea drilling vessel in the Arctic Ocean triggers a structural collapse, releasing a prehistoric thermal organism that feeds on geothermal heat.",
    thumbnailUrl: "https://images.unsplash.com/photo-1518098268026-4e43a1a009de?auto=format&fit=crop&w=800&q=80",
    videoUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    duration: 5800,
    releaseYear: 2024,
    rating: "18+",
    genres: ["Action & Adventure", "Drama & Suspense"],
    isTrending: true,
    isPopular: true,
    cast: ["Karl Urban", "Rebecca Ferguson", "Ciarán Hinds"],
    director: "John Carpenter",
    matchPercentage: 89,
    qualityTags: ["1080p", "Stereo"],
  },
  {
    id: "laughter-therapy",
    title: "Laughter Therapy",
    description: "An uptight neurosurgeon is mistakenly assigned to co-lead a chaotic stand-up comedy workshop in rural Ireland, turning both his career and perspective upside down.",
    thumbnailUrl: "https://images.unsplash.com/photo-1514306191717-452ec28c7814?auto=format&fit=crop&w=800&q=80",
    videoUrl: "https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8",
    duration: 6200,
    releaseYear: 2025,
    rating: "13+",
    genres: ["Comedy & Romance"],
    isTrending: false,
    isPopular: false,
    cast: ["Colin Farrell", "Saoirse Ronan", "Domhnall Gleeson"],
    director: "Martin McDonagh",
    matchPercentage: 91,
    qualityTags: ["1080p", "Dolby Atmos"],
  },
  {
    id: "planet-ocean",
    title: "Planet Ocean: Abyss",
    description: "Explore the deepest, most pressure-intense ocean trenches on Earth, uncovering strange bioluminescent creatures never before captured on ultra-high-definition lenses.",
    thumbnailUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    videoUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    duration: 3200,
    releaseYear: 2024,
    rating: "All",
    genres: ["Documentaries"],
    isTrending: false,
    isPopular: true,
    cast: ["David Attenborough"],
    director: "Alastair Fothergill",
    matchPercentage: 97,
    qualityTags: ["4K", "Ultra HD", "Dolby Atmos"],
  },
];

export const MOCK_PLANS: SubscriptionPlan[] = [
  {
    id: "basic-plan",
    name: "Basic Portal",
    price: 4.99,
    interval: "month",
    features: [
      "720p HD Streaming quality",
      "Watch on 1 device at a time",
      "Contains periodic ad highlights",
      "Access to full mock content catalog",
      "Mobile and tablet supported formats",
    ],
    isPopular: false,
  },
  {
    id: "standard-plan",
    name: "Standard Portal",
    price: 9.99,
    interval: "month",
    features: [
      "1080p Full HD Streaming quality",
      "Watch on 2 devices simultaneously",
      "100% Ad-free cinematic streaming",
      "Full access to 4K test trailers",
      "Offline downloads enabled",
    ],
    isPopular: true,
  },
  {
    id: "premium-plan",
    name: "Premium Portal",
    price: 14.99,
    interval: "month",
    features: [
      "4K Ultra HD & HDR resolution support",
      "Watch on 4 devices simultaneously",
      "Immersive Dolby Atmos 5.1 surround sound",
      "Exclusive early access to platform releases",
      "Priority customer help channels",
    ],
    isPopular: false,
  },
];
